# Bluetooth module Makefile fragment for openblue
# This file defines reusable variables and targets so that other projects (e.g. NuttX apps)
# can include it to compile the Bluetooth stack sources. It assumes .config exists and
# autoconf header has been generated by the including project's build.

# Detect repository root based on this module's location
BT_MK_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
BT_ROOT   ?= $(abspath $(BT_MK_DIR)/..)

# Platform selection: linux (default), nuttx, freertos (future)
BT_PLATFORM ?= linux

# Autoconf header path (generated by tools/kconfig in the root repo or the caller)
BT_AUTOCONF_H ?= $(BT_ROOT)/include/generated/autoconf.h

# Common include flags for Bluetooth stack
BT_CPPFLAGS := \
	-I$(BT_ROOT) \
	-I$(BT_ROOT)/include \
	-I$(BT_ROOT)/bluetooth \
	-I$(BT_ROOT)/bluetooth/host \
	-I$(BT_ROOT)/bluetooth/host/classic \
	-I$(BT_ROOT)/bluetooth/audio \
	-I$(BT_ROOT)/bluetooth/mesh \
	-I$(BT_ROOT)/bluetooth/services \
	-I$(BT_ROOT)/bluetooth/lib \
	-I$(BT_ROOT)/bluetooth/services/bas \
	-I$(BT_ROOT)/bluetooth/services/ias \
	-I$(BT_ROOT)/bluetooth/services/nus \
	-I$(BT_ROOT)/bluetooth/services/ots \

# Source selection mirrored from root Makefile (paths prefixed with $(BT_ROOT)/)
BT_SRCS :=

# Common sources
BT_SRCS_COMMON = \
	$(BT_ROOT)/bluetooth/common/addr.c \
	$(BT_ROOT)/bluetooth/common/dummy.c \
	$(BT_ROOT)/bluetooth/common/bt_str.c

ifeq ($(CONFIG_BT_RPA),y)
  BT_SRCS_COMMON += $(BT_ROOT)/bluetooth/common/rpa.c
endif
ifeq ($(CONFIG_BT_PRIVATE_SHELL),y)
  BT_SRCS_COMMON += $(BT_ROOT)/bluetooth/common/bt_shell_private.c
endif

# Crypto sources
BT_SRCS_CRYPTO =
ifeq ($(CONFIG_BT_CRYPTO),y)
  BT_SRCS_CRYPTO += \
	$(BT_ROOT)/bluetooth/crypto/bt_crypto.c \
	$(BT_ROOT)/bluetooth/crypto/bt_crypto_psa.c
endif

# Host sources
BT_SRCS_HOST =
ifeq ($(CONFIG_BT_HCI_HOST),y)
  BT_SRCS_HOST += \
	$(BT_ROOT)/bluetooth/host/uuid.c \
	$(BT_ROOT)/bluetooth/host/addr.c \
	$(BT_ROOT)/bluetooth/host/buf.c \
	$(BT_ROOT)/bluetooth/host/data.c \
	$(BT_ROOT)/bluetooth/host/hci_core.c \
	$(BT_ROOT)/bluetooth/host/hci_common.c \
	$(BT_ROOT)/bluetooth/host/id.c

  ifeq ($(CONFIG_BT_BROADCASTER),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/adv.c
  endif
  ifeq ($(CONFIG_BT_OBSERVER),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/scan.c
  endif
  ifeq ($(CONFIG_BT_HOST_CRYPTO),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/crypto_psa.c
  endif
  ifeq ($(CONFIG_BT_ECC),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/ecc.c
  endif

  ifeq ($(CONFIG_BT_CONN),y)
    BT_SRCS_HOST += \
	$(BT_ROOT)/bluetooth/host/conn.c \
	$(BT_ROOT)/bluetooth/host/l2cap.c \
	$(BT_ROOT)/bluetooth/host/att.c \
	$(BT_ROOT)/bluetooth/host/gatt.c

    ifeq ($(CONFIG_BT_SMP),y)
      BT_SRCS_HOST += \
	$(BT_ROOT)/bluetooth/host/smp.c \
	$(BT_ROOT)/bluetooth/host/keys.c
    else
      BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/smp_null.c
    endif
  endif

  ifeq ($(CONFIG_BT_ISO),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/iso.c
    ifneq ($(CONFIG_BT_CONN),y)
      BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/conn.c
    endif
  endif

  ifeq ($(CONFIG_BT_CHANNEL_SOUNDING),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/cs.c
  endif
  ifeq ($(CONFIG_BT_DF),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/direction.c
  endif
  ifeq ($(CONFIG_BT_HCI_RAW),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/hci_raw.c
  endif
  ifeq ($(CONFIG_BT_MONITOR),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/monitor.c
  endif
  ifeq ($(CONFIG_BT_SETTINGS),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/settings.c
  endif
  ifeq ($(CONFIG_BT_HOST_CCM),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/aes_ccm.c
  endif
  ifeq ($(CONFIG_BT_LONG_WQ),y)
    BT_SRCS_HOST += $(BT_ROOT)/bluetooth/host/long_wq.c
  endif
endif

# Host Classic sources
BT_SRCS_HOST_CLASSIC =
ifeq ($(CONFIG_BT_CLASSIC),y)
  BT_SRCS_HOST_CLASSIC += \
	$(BT_ROOT)/bluetooth/host/classic/br.c \
	$(BT_ROOT)/bluetooth/host/classic/conn_br.c \
	$(BT_ROOT)/bluetooth/host/classic/keys_br.c \
	$(BT_ROOT)/bluetooth/host/classic/l2cap_br.c \
	$(BT_ROOT)/bluetooth/host/classic/sdp.c \
	$(BT_ROOT)/bluetooth/host/classic/ssp.c \
	$(BT_ROOT)/bluetooth/host/classic/sco.c

  ifeq ($(CONFIG_BT_A2DP),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/a2dp.c $(BT_ROOT)/bluetooth/host/classic/a2dp_codec_sbc.c
  endif
  ifeq ($(CONFIG_BT_AVDTP),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/avdtp.c
  endif
  ifeq ($(CONFIG_BT_AVRCP),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/avrcp.c
  endif
  ifeq ($(CONFIG_BT_AVCTP),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/avctp.c
  endif
  ifeq ($(CONFIG_BT_RFCOMM),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/rfcomm.c
  endif
  ifeq ($(CONFIG_BT_HFP_HF),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/hfp_hf.c $(BT_ROOT)/bluetooth/host/classic/at.c
  endif
  ifeq ($(CONFIG_BT_HFP_AG),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/hfp_ag.c
  endif
  ifeq ($(CONFIG_BT_GOEP),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/obex.c $(BT_ROOT)/bluetooth/host/classic/goep.c
  endif
  ifeq ($(CONFIG_BT_DID),y)
    BT_SRCS_HOST_CLASSIC += $(BT_ROOT)/bluetooth/host/classic/did.c
  endif
endif

# Host Shell sources
BT_SRCS_HOST_SHELL =
ifeq ($(CONFIG_BT_SHELL),y)
  BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/shell/bt.c
  ifeq ($(CONFIG_BT_CONN),y)
    BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/shell/gatt.c
  endif
  ifeq ($(CONFIG_BT_L2CAP_DYNAMIC_CHANNEL),y)
    BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/shell/l2cap.c
  endif
  ifeq ($(CONFIG_BT_ISO),y)
    BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/shell/iso.c
  endif
  ifeq ($(CONFIG_BT_CHANNEL_SOUNDING),y)
    BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/shell/cs.c
  endif

  ifeq ($(CONFIG_BT_CLASSIC),y)
    BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/classic/shell/bredr.c
    ifeq ($(CONFIG_BT_RFCOMM),y)
      BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/classic/shell/rfcomm.c
    endif
    ifeq ($(CONFIG_BT_A2DP),y)
      BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/classic/shell/a2dp.c
    endif
    ifeq ($(CONFIG_BT_AVRCP),y)
      BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/classic/shell/avrcp.c
    endif
    ifneq ($(filter y,$(CONFIG_BT_HFP_HF) $(CONFIG_BT_HFP_AG)),)
      BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/classic/shell/hfp.c
    endif
    ifeq ($(CONFIG_BT_GOEP),y)
      BT_SRCS_HOST_SHELL += $(BT_ROOT)/bluetooth/host/classic/shell/goep.c
    endif
  endif
endif

# Audio sources
BT_SRCS_AUDIO =
ifeq ($(CONFIG_BT_AUDIO),y)
  BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/audio.c

  ifneq ($(filter y,$(CONFIG_BT_VOCS) $(CONFIG_BT_VOCS_CLIENT)),)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/vocs.c
  endif
  ifeq ($(CONFIG_BT_VOCS_CLIENT),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/vocs_client.c
  endif

  ifneq ($(filter y,$(CONFIG_BT_AICS) $(CONFIG_BT_AICS_CLIENT)),)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/aics.c
  endif
  ifeq ($(CONFIG_BT_AICS_CLIENT),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/aics_client.c
  endif

  ifeq ($(CONFIG_BT_VCP_VOL_REND),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/vcp_vol_rend.c
  endif
  ifeq ($(CONFIG_BT_VCP_VOL_CTLR),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/vcp_vol_ctlr.c
  endif

  ifeq ($(CONFIG_BT_MICP_MIC_DEV),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/micp_mic_dev.c
  endif
  ifeq ($(CONFIG_BT_MICP_MIC_CTLR),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/micp_mic_ctlr.c
  endif

  ifeq ($(CONFIG_BT_CONN),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/ccid.c
  endif

  ifeq ($(CONFIG_BT_CSIP_SET_MEMBER),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/csip_set_member.c
  endif
  ifeq ($(CONFIG_BT_CSIP_SET_COORDINATOR),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/csip_set_coordinator.c
  endif
  ifneq ($(filter y,$(CONFIG_BT_CSIP_SET_MEMBER) $(CONFIG_BT_CSIP_SET_COORDINATOR)),)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/csip_crypto.c
  endif

  ifeq ($(CONFIG_BT_TBS),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/tbs.c
  endif
  ifeq ($(CONFIG_BT_TBS_CLIENT),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/tbs_client.c
  endif
  ifeq ($(CONFIG_BT_MCC),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/mcc.c
  endif
  ifeq ($(CONFIG_BT_MCS),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/mcs.c
  endif
  ifeq ($(CONFIG_BT_MPL),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/mpl.c
  endif
  ifeq ($(CONFIG_MCTL),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/media_proxy.c
  endif
  ifeq ($(CONFIG_BT_ASCS),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/ascs.c
  endif
  ifeq ($(CONFIG_BT_PACS),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/pacs.c
  endif
  ifeq ($(CONFIG_BT_BAP_STREAM),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/bap_stream.c $(BT_ROOT)/bluetooth/audio/codec.c $(BT_ROOT)/bluetooth/audio/bap_iso.c
  endif
  ifeq ($(CONFIG_BT_BAP_BASE),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/bap_base.c
  endif
  ifeq ($(CONFIG_BT_BAP_UNICAST_SERVER),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/bap_unicast_server.c
  endif
  ifeq ($(CONFIG_BT_BAP_UNICAST_CLIENT),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/bap_unicast_client.c
  endif
  ifeq ($(CONFIG_BT_BAP_BROADCAST_SOURCE),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/bap_broadcast_source.c
  endif
  ifeq ($(CONFIG_BT_BAP_BROADCAST_SINK),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/bap_broadcast_sink.c
  endif
  ifeq ($(CONFIG_BT_BAP_SCAN_DELEGATOR),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/bap_scan_delegator.c
  endif
  ifeq ($(CONFIG_BT_BAP_BROADCAST_ASSISTANT),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/bap_broadcast_assistant.c
  endif
  ifeq ($(CONFIG_BT_CCP_CALL_CONTROL_CLIENT),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/ccp_call_control_client.c
  endif
  ifeq ($(CONFIG_BT_CCP_CALL_CONTROL_SERVER),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/ccp_call_control_server.c
  endif
  ifeq ($(CONFIG_BT_HAS),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/has.c
  endif
  ifeq ($(CONFIG_BT_HAS_CLIENT),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/has_client.c
  endif
  ifeq ($(CONFIG_BT_CAP),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/cap_stream.c
  endif
  ifeq ($(CONFIG_BT_CAP_ACCEPTOR),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/cap_acceptor.c
  endif
  ifeq ($(CONFIG_BT_CAP_INITIATOR),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/cap_initiator.c
  endif
  ifeq ($(CONFIG_BT_CAP_COMMANDER),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/cap_commander.c
  endif
  ifeq ($(CONFIG_BT_CAP_HANDOVER),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/cap_handover.c
  endif
  ifneq ($(filter y,$(CONFIG_BT_CAP_INITIATOR_UNICAST) $(CONFIG_BT_CAP_COMMANDER)),)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/cap_common.c
  endif
  ifeq ($(CONFIG_BT_TMAP),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/tmap.c
  endif
  ifeq ($(CONFIG_BT_GMAP),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/gmap_client.c $(BT_ROOT)/bluetooth/audio/gmap_server.c
  endif
  ifeq ($(CONFIG_BT_PBP),y)
    BT_SRCS_AUDIO += $(BT_ROOT)/bluetooth/audio/pbp.c
  endif
endif

# Audio Shell sources
BT_SRCS_AUDIO_SHELL =
ifeq ($(CONFIG_BT_SHELL),y)
  ifeq ($(CONFIG_BT_CCP_CALL_CONTROL_SERVER),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/ccp_call_control_server.c
  endif
  ifeq ($(CONFIG_BT_CCP_CALL_CONTROL_CLIENT),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/ccp_call_control_client.c
  endif
  ifeq ($(CONFIG_BT_VCP_VOL_REND),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/vcp_vol_rend.c
  endif
  ifeq ($(CONFIG_BT_VCP_VOL_CTLR),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/vcp_vol_ctlr.c
  endif
  ifeq ($(CONFIG_BT_MICP_MIC_DEV),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/micp_mic_dev.c
  endif
  ifeq ($(CONFIG_BT_MICP_MIC_CTLR),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/micp_mic_ctlr.c
  endif
  ifeq ($(CONFIG_BT_CSIP_SET_MEMBER),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/csip_set_member.c
  endif
  ifeq ($(CONFIG_BT_CSIP_SET_COORDINATOR),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/csip_set_coordinator.c
  endif
  ifeq ($(CONFIG_BT_TBS),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/tbs.c
  endif
  ifeq ($(CONFIG_BT_TBS_CLIENT),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/tbs_client.c
  endif
  ifeq ($(CONFIG_BT_MPL),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/mpl.c
  endif
  ifeq ($(CONFIG_BT_MCC),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/mcc.c
  endif
  ifeq ($(CONFIG_BT_MCS),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/media_controller.c
  endif
  ifeq ($(CONFIG_BT_HAS_PRESET_SUPPORT),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/has.c
  endif
  ifeq ($(CONFIG_BT_CAP_ACCEPTOR),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/cap_acceptor.c
  endif
  ifeq ($(CONFIG_BT_CAP_INITIATOR),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/cap_initiator.c
  endif
  ifeq ($(CONFIG_BT_CAP_COMMANDER),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/cap_commander.c
  endif
  ifeq ($(CONFIG_BT_HAS_CLIENT),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/has_client.c
  endif
  ifeq ($(CONFIG_BT_TMAP),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/tmap.c
  endif
  ifeq ($(CONFIG_BT_GMAP),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/gmap.c
  endif
  ifeq ($(CONFIG_BT_BAP_STREAM),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/bap.c
  endif
  ifeq ($(CONFIG_LIBLC3),y)
    ifeq ($(CONFIG_USBD_AUDIO2_CLASS),y)
      BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/bap_usb.c
    endif
  endif
  ifeq ($(CONFIG_BT_BAP_SCAN_DELEGATOR),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/bap_scan_delegator.c
  endif
  ifeq ($(CONFIG_BT_BAP_BROADCAST_ASSISTANT),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/bap_broadcast_assistant.c
  endif
  ifeq ($(CONFIG_BT_PBP),y)
    BT_SRCS_AUDIO_SHELL += $(BT_ROOT)/bluetooth/audio/shell/pbp.c
  endif
endif

# Services sources
BT_SRCS_SERVICES =
ifeq ($(CONFIG_BT_CONN),y)
  ifeq ($(CONFIG_BT_DIS),y)
    BT_SRCS_SERVICES += $(BT_ROOT)/bluetooth/services/dis.c
  endif
  ifeq ($(CONFIG_BT_CTS),y)
    BT_SRCS_SERVICES += $(BT_ROOT)/bluetooth/services/cts.c
  endif
  ifeq ($(CONFIG_BT_HRS),y)
    BT_SRCS_SERVICES += $(BT_ROOT)/bluetooth/services/hrs.c
  endif
  ifeq ($(CONFIG_BT_TPS),y)
    BT_SRCS_SERVICES += $(BT_ROOT)/bluetooth/services/tps.c
  endif
  # bas/ots/ias 位于子目录，后续如需细化可在此扩展
endif

# Mesh sources
BT_SRCS_MESH =
ifeq ($(CONFIG_BT_MESH),y)
  BT_SRCS_MESH += \
	$(BT_ROOT)/bluetooth/mesh/main.c \
	$(BT_ROOT)/bluetooth/mesh/cfg.c \
	$(BT_ROOT)/bluetooth/mesh/adv.c \
	$(BT_ROOT)/bluetooth/mesh/beacon.c \
	$(BT_ROOT)/bluetooth/mesh/net.c \
	$(BT_ROOT)/bluetooth/mesh/subnet.c \
	$(BT_ROOT)/bluetooth/mesh/app_keys.c \
	$(BT_ROOT)/bluetooth/mesh/heartbeat.c \
	$(BT_ROOT)/bluetooth/mesh/crypto.c \
	$(BT_ROOT)/bluetooth/mesh/crypto_psa.c \
	$(BT_ROOT)/bluetooth/mesh/access.c \
	$(BT_ROOT)/bluetooth/mesh/msg.c \
	$(BT_ROOT)/bluetooth/mesh/cfg_srv.c \
	$(BT_ROOT)/bluetooth/mesh/health_srv.c \
	$(BT_ROOT)/bluetooth/mesh/va.c \
	$(BT_ROOT)/bluetooth/mesh/transport.c

  ifeq ($(CONFIG_BT_MESH_ADV_LEGACY),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/adv_legacy.c
  endif
  ifeq ($(CONFIG_BT_MESH_ADV_EXT),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/adv_ext.c
  endif
  ifeq ($(CONFIG_BT_SETTINGS),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/settings.c
  endif
  ifeq ($(CONFIG_BT_MESH_RPL_STORAGE_MODE_SETTINGS),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/rpl.c
  endif
  ifeq ($(CONFIG_BT_MESH_LOW_POWER),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/lpn.c
  endif
  ifeq ($(CONFIG_BT_MESH_FRIEND),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/friend.c
  endif
  ifeq ($(CONFIG_BT_MESH_PROV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/prov.c
  endif
  ifeq ($(CONFIG_BT_MESH_PROVISIONEE),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/provisionee.c
  endif
  ifeq ($(CONFIG_BT_MESH_PROVISIONER),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/provisioner.c
  endif
  ifeq ($(CONFIG_BT_MESH_PB_ADV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/pb_adv.c
  endif
  ifeq ($(CONFIG_BT_MESH_PB_GATT_COMMON),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/pb_gatt.c
  endif
  ifeq ($(CONFIG_BT_MESH_PB_GATT),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/pb_gatt_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_PB_GATT_CLIENT),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/pb_gatt_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_GATT_CLIENT),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/gatt_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_PROXY_CLIENT),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/proxy_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_GATT_PROXY),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/proxy_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_GATT),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/proxy_msg.c
  endif
  ifeq ($(CONFIG_BT_MESH_CFG_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/cfg_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_HEALTH_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/health_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_SAR_CFG_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/sar_cfg_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_SAR_CFG_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/sar_cfg_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_SAR_CFG),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/sar_cfg.c
  endif
  ifeq ($(CONFIG_BT_MESH_OP_AGG_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/op_agg_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_OP_AGG_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/op_agg_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_OP_AGG),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/op_agg.c
  endif
  ifeq ($(CONFIG_BT_MESH_LARGE_COMP_DATA_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/large_comp_data_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_LARGE_COMP_DATA_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/large_comp_data_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_PRIV_BEACON_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/priv_beacon_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_PRIV_BEACON_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/priv_beacon_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_SELF_TEST),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/test.c
  endif
  ifeq ($(CONFIG_BT_MESH_CDB),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/cdb.c
  endif
  ifeq ($(CONFIG_BT_MESH_BLOB_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/blob_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_BLOB_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/blob_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_BLOB_IO_FLASH),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/blob_io_flash.c
  endif
  ifeq ($(CONFIG_BT_MESH_DFU_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/dfu_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_DFU_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/dfu_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_DFD_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/dfd_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_DFU_SLOTS),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/dfu_slot.c
  endif
  ifeq ($(CONFIG_BT_MESH_DFU_METADATA),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/dfu_metadata.c
  endif
  ifeq ($(CONFIG_BT_MESH_RPR_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/rpr_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_RPR_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/rpr_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_OD_PRIV_PROXY_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/od_priv_proxy_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_OD_PRIV_PROXY_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/od_priv_proxy_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_SOL_PDU_RPL_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/sol_pdu_rpl_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_OD_PRIV_PROXY_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/sol_pdu_rpl_srv.c
  endif
  ifeq ($(CONFIG_BT_MESH_BRG_CFG_CLI),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/brg_cfg_cli.c
  endif
  ifeq ($(CONFIG_BT_MESH_BRG_CFG_SRV),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/brg_cfg_srv.c $(BT_ROOT)/bluetooth/mesh/brg_cfg.c
  endif
  ifeq ($(CONFIG_BT_MESH_SOLICITATION),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/solicitation.c
  endif
  ifeq ($(CONFIG_BT_MESH_STATISTIC),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/statistic.c
  endif
  ifeq ($(CONFIG_BT_MESH_ACCESS_DELAYABLE_MSG),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/delayable_msg.c
  endif
  ifeq ($(CONFIG_BT_TESTING),y)
    BT_SRCS_MESH += $(BT_ROOT)/bluetooth/mesh/testing.c
  endif
endif

# Lib sources
BT_SRCS_LIB =
ifeq ($(CONFIG_BT_EAD),y)
  BT_SRCS_LIB += $(BT_ROOT)/bluetooth/lib/ead.c
endif

# Platform-specific additions
ifeq ($(BT_PLATFORM),linux)
  BT_SRCS_PLATFORM := \
	$(BT_ROOT)/osdep/posix/os.c \
	$(BT_ROOT)/drivers/hci_sock.c \
	$(BT_ROOT)/drivers/userchan.c
else ifeq ($(BT_PLATFORM),nuttx)
  BT_SRCS_PLATFORM := \
	$(BT_ROOT)/osdep/posix/os.c \
	$(BT_ROOT)/drivers/h4.c
else ifeq ($(BT_PLATFORM),freertos)
  BT_SRCS_PLATFORM := \
	$(BT_ROOT)/osdep/freertos/os.c
else
  $(warning Unknown BT_PLATFORM '$(BT_PLATFORM)'; defaulting to linux)
  BT_SRCS_PLATFORM := \
	$(BT_ROOT)/osdep/posix/os.c \
	$(BT_ROOT)/drivers/hci_sock.c
endif

# Combine all bluetooth-related sources
BT_SRCS += \
	$(BT_SRCS_PLATFORM) \
	$(BT_SRCS_COMMON) \
	$(BT_SRCS_CRYPTO) \
	$(BT_SRCS_HOST) \
	$(BT_SRCS_HOST_CLASSIC) \
	$(BT_SRCS_HOST_SHELL) \
	$(BT_SRCS_AUDIO) \
	$(BT_SRCS_AUDIO_SHELL) \
	$(BT_SRCS_SERVICES) \
	$(BT_SRCS_MESH) \
	$(BT_SRCS_LIB)

# Objects and deps for this module library (standalone use)
BT_OBJS := $(BT_SRCS:.c=.o)
BT_DEPS := $(BT_OBJS:.o=.d)

# Phony clean for module artifacts
.PHONY: bt-clean
bt-clean:
	$(RM) $(BT_OBJS) $(BT_DEPS) libopenblue_bt.a

# Static library rule for standalone builds (caller must provide compile rules)
libopenblue_bt.a: $(BT_OBJS)
	@echo "AR $@"
	$(AR) rcs $@ $(BT_OBJS)
