add_subdirectory(addr)
add_subdirectory(audio/ccid)
add_subdirectory(audio/codec)
add_subdirectory(bt_crypto_ccm)
add_subdirectory(gap)
add_subdirectory(hci)
add_subdirectory(uuid)
add_subdirectory(host/data/bt_data_parse)
add_subdirectory(host/crypto/bt_rand)
add_subdirectory(host/crypto/bt_encrypt_be)
add_subdirectory(host/crypto/bt_encrypt_le)
add_subdirectory(host/cs/bt_le_cs_parse_pct)
add_subdirectory(host/cs/bt_le_cs_set_valid_chmap_bits)
add_subdirectory(host/cs/bt_le_cs_step_data_parse)
add_subdirectory(host/id/bt_id_get)
add_subdirectory(host/id/bt_lookup_id_addr)
add_subdirectory(host/id/bt_le_oob_set_legacy_tk)
add_subdirectory(host/id/bt_br_oob_get_local)
