# CMake helper macros/functions

# Compute a unique object library name for the current source directory
function(_openblue_compute_current_target out_var)
  # Compute relative dir from source root
  file(RELATIVE_PATH _rel_dir "${CMAKE_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
  if(NOT _rel_dir OR _rel_dir STREQUAL ".")
    set(_rel_dir "root")
  endif()
  string(REPLACE "/" "_" _rel_id "${_rel_dir}")
  set(_tgt "openblue_obj_${_rel_id}")
  set(${out_var} "${_tgt}" PARENT_SCOPE)
endfunction()

# Ensure a per-directory object library exists and store as directory property
function(openblue_library)
  _openblue_compute_current_target(_tgt)
  if(NOT TARGET ${_tgt})
    add_library(${_tgt} INTERFACE)
  endif()
  # Store current target in directory property
  set_property(DIRECTORY PROPERTY STACK_CURRENT_TARGET ${_tgt})
endfunction()

# Internal: get current target or create
function(_openblue_ensure_current_target out_var)
  get_property(_cur_tgt DIRECTORY PROPERTY STACK_CURRENT_TARGET)
  if(NOT _cur_tgt)
    openblue_library()
    get_property(_cur_tgt DIRECTORY PROPERTY STACK_CURRENT_TARGET)
  endif()
  set(${out_var} "${_cur_tgt}" PARENT_SCOPE)
endfunction()

# Add sources to the per-directory object library
function(openblue_library_sources)
  _openblue_ensure_current_target(_tgt)
  if(ARGC GREATER 0)
    target_sources(${_tgt} INTERFACE ${ARGV})
  endif()
endfunction()

# Conditionally add sources based on CONFIG symbol
function(openblue_library_sources_ifdef symbol)
  _openblue_ensure_current_target(_tgt)
  if(DEFINED ${symbol} AND ${symbol})
    if(ARGC GREATER 1)
      # Remaining args are sources
      list(REMOVE_AT ARGV 0)
      target_sources(${_tgt} INTERFACE ${ARGV})
    endif()
  endif()
endfunction()

# Link libraries to the per-directory object library (no-op at build time, safe at configure)
function(openblue_library_link_libraries)
  _openblue_ensure_current_target(_tgt)
  if(ARGC GREATER 0)
    target_link_libraries(${_tgt} INTERFACE ${ARGV})
  endif()
endfunction()

# Conditionally link libraries
function(openblue_library_link_libraries_ifdef symbol)
  _openblue_ensure_current_target(_tgt)
  if(DEFINED ${symbol} AND ${symbol})
    if(ARGC GREATER 1)
      list(REMOVE_AT ARGV 0)
      target_link_libraries(${_tgt} INTERFACE ${ARGV})
    endif()
  endif()
endfunction()

# Conditionally add include directories
function(openblue_library_include_directories_ifdef symbol)
  _openblue_ensure_current_target(_tgt)
  if(DEFINED ${symbol} AND ${symbol})
    if(ARGC GREATER 1)
      list(REMOVE_AT ARGV 0)
      target_include_directories(${_tgt} INTERFACE ${ARGV})
    endif()
  endif()
endfunction()

# Project-wide include directories (simple wrapper)
function(openblue_include_directories)
  if(ARGC GREATER 0)
    include_directories(${ARGV})
  endif()
endfunction()

# Conditionally add a subdirectory based on a CONFIG symbol
function(openblue_add_subdirectory_ifdef symbol dir)
  if(DEFINED ${symbol} AND ${symbol})
    add_subdirectory(${dir})
  endif()
endfunction()

# Load Kconfig .config into CMake variables and compile definitions
# - For each CONFIG_FOO=y: set(CONFIG_FOO 1) and add_compile_definitions(CONFIG_FOO=1)
# - For CONFIG_FOO=n or unset: set(CONFIG_FOO 0) (no compile definition)
# - For CONFIG_INT=123: set(CONFIG_INT 123) and add_compile_definitions(CONFIG_INT=123)
# - For CONFIG_STR="abc": set(CONFIG_STR "abc"); define CONFIG_STR="abc" as compile definition
function(openblue_load_kconfig config_path)
  # Auto-create a minimal .config if not present
  if(NOT EXISTS "${config_path}")
    message(STATUS "Stack: .config not found at ${config_path}. Please run 'make genconfig' to generate it.")
  endif()

  file(STRINGS "${config_path}" _lines)
  set(_def_header "${CMAKE_BINARY_DIR}/include/generated/autoconf.h")
  file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/include/generated")
  file(WRITE "${_def_header}" "/* Auto-generated by openblue_load_kconfig */\n")

  foreach(_line IN LISTS _lines)
    string(STRIP "${_line}" _s)
    if(_s MATCHES "^# CONFIG_[A-Za-z0-9_]+ is not set$")
      string(REGEX REPLACE "^# (CONFIG_[A-Za-z0-9_]+) is not set$" "\\1" _sym "${_s}")
      set(${_sym} 0)
      set(${_sym} 0 PARENT_SCOPE)
      # Do not define macro for n
      continue()
    endif()

    if(_s MATCHES "^(CONFIG_[A-Za-z0-9_]+)=(.*)$")
      string(REGEX REPLACE "^(CONFIG_[A-Za-z0-9_]+)=(.*)$" "\\1" _sym "${_s}")
      string(REGEX REPLACE "^(CONFIG_[A-Za-z0-9_]+)=(.*)$" "\\2" _val "${_s}")
      # Normalize values
      if(_val STREQUAL "y")
        set(${_sym} 1)
        set(${_sym} 1 PARENT_SCOPE)
        add_compile_definitions(${_sym}=1)
        file(APPEND "${_def_header}" "#define ${_sym} 1\n")
      elseif(_val STREQUAL "n")
        set(${_sym} 0)
        set(${_sym} 0 PARENT_SCOPE)
        # no definition for n
      else()
        # Numeric or quoted string
        set(${_sym} ${_val})
        set(${_sym} ${_val} PARENT_SCOPE)
        # Add compile definition as-is
        add_compile_definitions(${_sym}=${_val})
        file(APPEND "${_def_header}" "#define ${_sym} ${_val}\n")
      endif()
    endif()
  endforeach()

  # Expose generated header include dir for any future compile steps
  include_directories("${CMAKE_BINARY_DIR}/include/generated")

  message(STATUS "Stack: loaded Kconfig from ${config_path}")
endfunction()

# Unconditional include directories for the current per-directory target
function(openblue_library_include_directories)
  _openblue_ensure_current_target(_tgt)
  if(ARGC GREATER 0)
    target_include_directories(${_tgt} INTERFACE ${ARGV})
  endif()
endfunction()

# Optional: register current per-directory target to a global list for aggregation
function(openblue_register_current_target)
  _openblue_ensure_current_target(_tgt)
  get_property(_reg GLOBAL PROPERTY STACK_REGISTERED_TARGETS)
  if(NOT _reg)
    set(_reg "")
  endif()
  list(APPEND _reg ${_tgt})
  set_property(GLOBAL PROPERTY STACK_REGISTERED_TARGETS "${_reg}")
endfunction()

# Retrieve all registered per-directory targets
function(openblue_get_registered_targets out_var)
  get_property(_reg GLOBAL PROPERTY STACK_REGISTERED_TARGETS)
  if(NOT _reg)
    set(_reg "")
  endif()
  set(${out_var} "${_reg}" PARENT_SCOPE)
endfunction()